# Generated by Django 5.0.3 on 2024-04-07 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_auction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="won_auctions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
