# Generated by Django 5.0.3 on 2024-04-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_auction_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="cover",
            field=models.ImageField(upload_to="uploads/"),
        ),
    ]
