# Generated by Django 5.0.3 on 2024-04-09 14:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0006_user_birthday_user_cellphone_number_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="comments",
            new_name="Comment",
        ),
    ]
