# Generated by Django 5.0.3 on 2024-04-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0008_remove_user_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="category",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
