# Generated by Django 5.0.3 on 2024-04-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0010_alter_auction_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="cover",
            field=models.ImageField(upload_to="covers/"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="image",
            field=models.ImageField(upload_to="comments/"),
        ),
    ]
