# Generated by Django 5.0.3 on 2024-04-13 17:06

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0012_alter_auction_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="cover",
            field=models.ImageField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="/media/covers"
                ),
                upload_to="",
            ),
        ),
    ]
