# Generated by Django 5.0.3 on 2024-04-19 22:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0019_comment_timestamp_alter_comment_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email_address",
        ),
    ]
